### PR TITLE
finish base, index, login, signup frontend pages

### PR DESCRIPTION
**Pull request by allison-lee6444**

### CODE REVIEW

**Comment by meoriordan** [comment]
I think for the device page if a user wants to add a new device they should pick from existing devices and existing locations? I had originally implemented that as 2 drop downs. Other than that this looks good!

**Comment by allison-lee6444** [comment]
> I think for the device page if a user wants to add a new device they should pick from existing devices and existing locations? I had originally implemented that as 2 drop downs. Other than that this looks good!

oh im still working on it. ive asked whether i should create a table or use select distinct on discord, so if u can lmk wt u think it would be great.

also, i think i would need some time to figure out the selection part, making sure the user input always match the expected pair. so just need to learn some jinja and vanilla html and js to do this..

**Comment by meoriordan** [comment]
The way I had done it was to show all devices currently in the device table, and all locations tied to the customer_id that is logged in. Did you have something else in mind?

**Comment by allison-lee6444** [comment]
> The way I had done it was to show all devices currently in the device table, and all locations tied to the customer_id that is logged in. Did you have something else in mind?

im actually thinking of doing tabs of location and it will show u the devices in that particular location. i think this is more organized. do u hv any thoughts for my previous comment btw?

**Pull request merged**
